CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    merchant VARCHAR(255) NOT NULL,

    amount NUMERIC(12, 2) NOT NULL
        CHECK (amount > 0),
    
    transaction_date DATE NOT NULL,

    category VARCHAR(50) NOT NULL,

    source_type VARCHAR(50) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);